/** Every string of site chrome. Content prose lives with the content. */
export const ui = {
  nav: {
    work: "Work",
    about: "About",
    contact: "Contact",
  } satisfies Record<string, string>,
  common: {
    skipToContent: "Skip to content",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    toInk: "Switch to ink theme",
    toPaper: "Switch to paper theme",
    paper: "Paper",
    ink: "Ink",
    stage: "Stage",
    thesis: "Thesis",
    evidence: "Evidence",
    method: "Method",
    position: "Position",
    theLoop: "The loop",
    allWork: "All work",
    readCase: "Read the case",
    source: "Source",
    nextCase: "Next case",
    role: "Role",
    span: "Span",
    status: "Status",
    team: "Team",
    solo: "Solo",
    now: "now",
    interactive: "Interactive",
    selected: "Selected",
    downloadCv: "Download CV",
    cvPdf: "CV (PDF)",
    site: "Site",
    elsewhere: "Elsewhere",
    currently: "Currently",
    architecture: "Architecture",
    decisionLog: "Decision log",
    tradeoff: "Tradeoff",
    why: "Why",
    revisitIf: "Revisit if",
    entries: "entries",
    fromTheField: "From the field",
    whatChanged: "What changed",
    rebuildToday: "If I rebuilt it today",
    caseSingular: "case",
    casePlural: "cases",
    atThisStage: "at this stage",
    all: "All",
    backTo01: "back to 01 — Signal",
    performanceBudget: "Performance budget",
  } satisfies Record<string, string>,
  home: {
    heroWord: "Whole",
    heroPron: "/hōl/ · noun",
    heroDefinition: "the whole formed by the combination of all its parts.",
    heroStatementLead: "That’s the job. Not the code, not the plan —",
    heroStatementBold: "the combination.",
    heroStatementRest: "I find the need, define the shape, plan the path, build the thing, prove it works, and fix what the field says is wrong.",
    seeTheLoop: "See the loop",
    theEvidence: "The evidence",
    skipTheLoop: "Skip the loop ↓",
    loopHeading: "Six stages. Most people own two of them.",
    loopIntro: "Industrial Engineering calls this a value stream. It is the same six steps every time, and the value is in owning all of them — including the last one, which is where projects become products.",
    evidenceHeading: "Three products. Every claim above is one of these.",
    evidenceIntro: "Each carries a decision log — what I chose, what I gave up for it, and the condition that would make me change my mind.",
    positionQuoteLead: "Software Engineering gave me the build. Industrial Engineering gave me the system.",
    positionQuoteAccent: "The value is the combination.",
    positionBody: [
      "Two degrees that read as unrelated are one argument: software is the tool, systems are the subject. I did not move away from engineering — I went and got the half that makes engineering land.",
    ] satisfies string[],
    seeHowIWork: "See how I work →",
    classroomLabel: "The classroom",
    classroomHeading: "I learned requirements in front of a room of sixteen-year-olds.",
    classroomBody: [
      "Teaching programming, alongside work on syllabuses, lesson plans, exercises and instructor guides, has been the most useful professional training I have had — and not for the reason people assume.",
      "Teaching is requirements engineering with a thirty-second feedback loop. A room shows you immediately which part of an explanation was carrying a hidden assumption.",
      "But a room never learns in one way. Every student arrives with a different starting point, pace and way of making sense of a problem. I learned to change the wording, sequence, medium or level of abstraction until the idea lands — without changing the goal.",
      "That habit travels beyond the classroom. Students, instructors, coordinators, clients and engineers do not need the same explanation or interface. Understanding the audience is part of understanding the requirement.",
    ] satisfies string[],
    classroomRule: "A requirement is not finished until the people it is for can understand and use it.",
  },
  work: {
    title: "Work",
    intro: "Four substantial case studies, followed by the earlier engineering work that built the craft. Start with the decision; open the evidence when you want the depth.",
    selectedTitle: "Selected work",
    selectedIntro: "The work that best shows what was broken, what I owned, how I built and what can be inspected today.",
    filterNote: "Filtered by stage of delivery, not by technology — because the stack is the least interesting thing about any of these.",
    empty: "Nothing at this stage yet. That is the honest answer rather than a padded one.",
    repsTitle: "Earlier engineering work",
    repsSpan: "2022 — 2024 · University",
    repsHeading: "Foundations, at the right weight.",
    repsIntro: "University projects stay visible for technical reviewers without competing with the work that best represents me now.",
    colProject: "Project",
    colSpan: "Span",
    colStack: "Stack",
    colTaught: "What it taught",
  },
  system: {
    title: "System",
    intro: "Delivery is not a talent, it is a process — and a process can be written down, taught, and improved. This is mine. It is the same six stages every time, and it is the reason the work on this site looks consistent despite spanning education, infrastructure and consumer product.",
    sixStages: "The six stages",
    produces: "What this stage produces",
    peopleTitle: "Working with people",
    peopleHeading: "Most requirements fail as translation, not as analysis.",
    peopleBody: [
      "When a client and a developer disagree, it is almost never because one of them is wrong. It is because a word in the spec means two different things and nobody has noticed yet. My job in that room is to find the word.",
      "So I write things down, in plain language, and read them back to the people who will live with the result. It is unglamorous and it prevents most of the expensive failures.",
    ] satisfies string[],
    nextTitle: "Where to look next",
    nextEvidence: "The evidence",
    nextEvidenceBody: "Case studies filtered by stage, each with a decision log and a rebuild list.",
    nextThesis: "The thesis",
    nextThesisBody: "Why a software engineer went and got an Industrial Engineering degree.",
  },
  about: {
    title: "About",
    lede: "I work where product decisions, systems and implementation stop being separate conversations.",
    thesisLabel: "The thesis",
    thesisBody: [
      "I completed a B.Sc. in Software Engineering and am now studying toward an M.Sc. in Industrial Engineering & Management. That is not a pivot away from engineering; it is a closer look at what engineering is for.",
      "Industrial Engineering is the discipline of designing, measuring and improving systems and processes. It is the formal version of the thing I kept running into at work: the code was rarely the bottleneck. The bottleneck was an undefined requirement, a handoff nobody owned, or a workaround that had quietly become policy. I had been solving those problems by instinct. I went and learned to do it properly.",
      "So the two degrees are one argument. **Software is the tool. Systems are the subject.** Being able to write the code is what stops the systems thinking from becoming a slide deck; understanding the system is what stops the code from being beautifully built and pointed at the wrong problem.",
      "In practice this means I am not looking for a role where I only write tickets, and not one where I only close them. The work I am good at is the whole loop — finding the need, framing it, sequencing it, building it, proving it, and then sitting with the people who use it while they tell me what I got wrong.",
    ] satisfies string[],
    teachingLabel: "What teaching taught me",
    wantLabel: "What I want next",
    wantBody: [
      "A technical product role, on a small team, where the distance between noticing a problem and shipping something about it is short. I want to own outcomes rather than tickets, and I want to be close enough to the users that the feedback arrives directly rather than through a summary.",
      "I am comfortable being the person who writes the spec and then has to implement it. I think that combination is rarer than it should be, and it is the entire reason this site is organised the way it is.",
    ] satisfies string[],
    getInTouch: "Get in touch →",
    experienceTitle: "Experience",
    educationTitle: "Education",
    detailsHint: "Hover, focus or tap a role to read the details.",
    currentRole: "Current role",
    currentStudies: "Current studies",
    roleDetails: "Role details",
    closeDetails: "Close details",
    responsibilities: "What I do",
    fitTitle: "Where I do my best work",
  },
  contact: {
    title: "Contact",
    lede: "If the role needs someone who can move from the real problem to a shipped system, let’s talk.",
    based: "Based",
    basedValue: "Israel time\nSunday to Thursday",
    lookingFor: "Looking for",
    lookingForValue: "Technical product roles on small teams. Discovery through delivery, with the iteration after it.",
    cv: "CV",
    downloadPdf: "Download PDF ↓",
    briefTitle: "The brief",
    briefHeading: "The job description I would write, if I were writing it.",
    briefIntro: "Most candidates read a role spec and try to match it. I find it more useful to publish mine, so we can both see the gap early rather than four weeks into a process.",
    footerNote: "Open to technical product and product-minded engineering roles with real ownership, close users and room to build.",
  },
  notFound: {
    label: "No route",
    title: "Nothing here.",
    body: "This page does not exist, which is a small failure at the Prove stage. The work is where you probably meant to go.",
    cta: "See the work →",
    home: "Home",
  },
} as const;
export type UI = typeof ui;
