import type { Project } from "@/lib/types";

/**
 * University coursework, 2022–2023. Kept deliberately compact — these are reps,
 * not products, and weighting them correctly is part of the point.
 */
export const reps: Project[] = [
  {
    slug: "hr-organization",
    title: "HRIS",
    oneLiner: {
      en: "Employee, delivery and shift management for retail stores.",
      he: "ניהול עובדים, משלוחים ומשמרות לחנויות קמעונאיות.",
    },
    hook: { en: "", he: "" },
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: { en: "University project", he: "פרויקט אוניברסיטאי" },
    started: "2023-01",
    ended: "2023-07",
    status: "archived",
    metrics: [],
    stack: ["Java", "SQL", "Layered architecture"],
    links: { repo: "https://github.com/tnaydnov/HR_Organization" },
    taught: {
      en: "Scheduling is a constraint-satisfaction problem, and most of the difficulty lives in the rules people never write down.",
      he: "שיבוץ הוא בעיית סיפוק אילוצים, ורוב הקושי נמצא בכללים שאנשים אף פעם לא כותבים.",
    },
  },
  {
    slug: "kanban",
    title: "Kanban",
    oneLiner: {
      en: "A board-based task and workflow tool.",
      he: "כלי משימות ותהליכים מבוסס לוח.",
    },
    hook: { en: "", he: "" },
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: { en: "University project", he: "פרויקט אוניברסיטאי" },
    started: "2022-09",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["C#", ".NET", "Layered architecture"],
    links: { repo: "https://github.com/tnaydnov/Kanban" },
    taught: {
      en: "A test suite written after the fact documents what the code does. Written first, it documents what it should do.",
      he: "חבילת טסטים שנכתבת בדיעבד מתעדת מה הקוד עושה. אם נכתבת קודם, היא מתעדת מה הוא אמור לעשות.",
    },
  },
  {
    slug: "set-card-game",
    title: "Set",
    oneLiner: {
      en: "Concurrent implementation of the Set card game.",
      he: "מימוש מקבילי של משחק הקלפים Set.",
    },
    hook: { en: "", he: "" },
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: { en: "University project", he: "פרויקט אוניברסיטאי" },
    started: "2022-10",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["Java", "Concurrency", "Threading"],
    links: { repo: "https://github.com/tnaydnov/Set_Card_Game" },
    taught: {
      en: "Concurrency bugs are not bugs in the code you wrote, they are bugs in the assumptions you did not know you had.",
      he: "באגים של מקביליות הם לא באגים בקוד שכתבת, הם באגים בהנחות שלא ידעת שיש לך.",
    },
  },
  {
    slug: "dungeons-and-dragons",
    title: "Dungeons & Dragons",
    oneLiner: {
      en: "A turn-based RPG engine with characters, combat and progression.",
      he: "מנוע משחק תפקידים מבוסס תורות עם דמויות, קרב והתקדמות.",
    },
    hook: { en: "", he: "" },
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: { en: "University project", he: "פרויקט אוניברסיטאי" },
    started: "2022-09",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["Java", "OOP", "Design patterns"],
    links: { repo: "https://github.com/tnaydnov/Dungeons_and_Dragons" },
    taught: {
      en: "Inheritance modelled on nouns collapses fast. Behaviour is the thing worth composing.",
      he: "ירושה שממודלת לפי שמות עצם קורסת מהר. התנהגות היא הדבר ששווה להרכיב.",
    },
  },
  {
    slug: "the-coalition-race",
    title: "The Coalition Race",
    oneLiner: {
      en: "A turn-based political strategy simulation.",
      he: "סימולציית אסטרטגיה פוליטית מבוססת תורות.",
    },
    hook: { en: "", he: "" },
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: { en: "University project", he: "פרויקט אוניברסיטאי" },
    started: "2022-09",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["C++", "Memory management", "OOP"],
    links: { repo: "https://github.com/tnaydnov/The_Coalition_Race" },
    taught: {
      en: "Owning memory manually teaches you what every garbage-collected language is quietly doing on your behalf.",
      he: "ניהול זיכרון ידני מלמד אותך מה כל שפה עם איסוף זבל עושה בשקט בשבילך.",
    },
  },
];
