import type { Project } from "@/lib/types";

/**
 * University coursework, 2022–2023. Kept deliberately compact — these are reps,
 * not products, and weighting them correctly is part of the point.
 */
export const reps: Project[] = [
  {
    slug: "hr-organization",
    title: "HRIS",
    oneLiner:
      "Employee, delivery and shift management for retail stores.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2023-01",
    ended: "2023-07",
    status: "archived",
    metrics: [],
    stack: ["Java", "SQL", "Layered architecture"],
    links: { repo: "https://github.com/tnaydnov/HR_Organization" },
    taught:
      "Scheduling is a constraint-satisfaction problem, and most of the difficulty lives in the rules people never write down.",
  },
  {
    slug: "kanban",
    title: "Kanban",
    oneLiner: "A board-based task and workflow tool.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022-09",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["C#", ".NET", "Layered architecture"],
    links: { repo: "https://github.com/tnaydnov/Kanban" },
    taught:
      "A test suite written after the fact documents what the code does. Written first, it documents what it should do.",
  },
  {
    slug: "set-card-game",
    title: "Set",
    oneLiner: "Concurrent implementation of the Set card game.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022-10",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["Java", "Concurrency", "Threading"],
    links: { repo: "https://github.com/tnaydnov/Set_Card_Game" },
    taught:
      "Concurrency bugs are not bugs in the code you wrote, they are bugs in the assumptions you did not know you had.",
  },
  {
    slug: "dungeons-and-dragons",
    title: "Dungeons & Dragons",
    oneLiner: "A turn-based RPG engine with characters, combat and progression.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022-09",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["Java", "OOP", "Design patterns"],
    links: { repo: "https://github.com/tnaydnov/Dungeons_and_Dragons" },
    taught:
      "Inheritance modelled on nouns collapses fast. Behaviour is the thing worth composing.",
  },
  {
    slug: "the-coalition-race",
    title: "The Coalition Race",
    oneLiner: "A turn-based political strategy simulation.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022-09",
    ended: "2022-12",
    status: "archived",
    metrics: [],
    stack: ["C++", "Memory management", "OOP"],
    links: { repo: "https://github.com/tnaydnov/The_Coalition_Race" },
    taught:
      "Owning memory manually teaches you what every garbage-collected language is quietly doing on your behalf.",
  },
];
