import type { Project } from "@/lib/types";
/** Archived university coursework, 2022–2023. */
export const reps: Project[] = [
  {
    slug: "hr-organization",
    title: "HRIS",
    oneLiner: "Employee, delivery and shift management for retail stores.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2023",
    ended: "2023",
    status: "archived",
    metrics: [],
    stack: ["Java"],
    links: { repo: "https://github.com/tnaydnov/HR_Organization" },
    taught: "Modeling the staffing and delivery rules behind a workable schedule.",
  },
  {
    slug: "kanban",
    title: "Kanban",
    oneLiner: "A Kanban task-management backend with a partial desktop frontend.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022",
    ended: "2022",
    status: "archived",
    metrics: [],
    stack: ["C#", ".NET"],
    links: { repo: "https://github.com/tnaydnov/Kanban" },
    taught: "Defining task and board behavior through layered code and tests.",
  },
  {
    slug: "set-card-game",
    title: "Set",
    oneLiner: "Concurrent implementation of the Set card game.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022",
    ended: "2022",
    status: "archived",
    metrics: [],
    stack: ["Java", "Concurrency", "Threading"],
    links: { repo: "https://github.com/tnaydnov/Set_Card_Game" },
    taught: "Coordinating player and dealer threads around shared game state.",
  },
  {
    slug: "dungeons-and-dragons",
    title: "Dungeons & Dragons",
    oneLiner: "A turn-based RPG engine with characters, combat and progression.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022",
    ended: "2022",
    status: "archived",
    metrics: [],
    stack: ["Java", "OOP"],
    links: { repo: "https://github.com/tnaydnov/Dungeons_and_Dragons" },
    taught: "Separating characters, combat rules, and progression in an object-oriented model.",
  },
  {
    slug: "the-coalition-race",
    title: "The Coalition Race",
    oneLiner: "A turn-based political strategy simulation.",
    hook: "",
    tier: "rep",
    stages: ["build"],
    domain: ["platform"],
    role: "University project",
    started: "2022",
    ended: "2022",
    status: "archived",
    metrics: [],
    stack: ["C++", "OOP"],
    links: { repo: "https://github.com/tnaydnov/The_Coalition_Race" },
    taught: "Making ownership and object lifetime explicit in C++.",
  },
];
