import type { ProjectWorld } from "./worlds";
export const applytideWorld: ProjectWorld = {
  headline:"Find it. Make it yours. Move it forward.",
  description:"A personal workspace for a job search: capture a posting in your browser, prepare your documents for that role and keep the application’s next step in view.",
  motif:"THE PERSONAL JOB-SEARCH WORKSPACE",roles:["Job seekers", "One account, one search"],hero:"pipeline",companion:"extension-saved",
  repo:"https://github.com/tnaydnov/Applytide",revision:"a040d14d5c45491e3db1651c0d4daa67a218c32f",
  stories:[
    {id:"capture",label:"Capture the opportunity",title:"That promising tab becomes a real plan.",description:"Save a fictional Northstar Studio posting with the actual installed extension. The role, company and location arrive in the same personal workspace, ready for a closer look.",film:"extension-intake",screens:["extension-saved","captured-job-details"],takeaway:{title:"Start with what the page already knows.",text:"Structured job data, the rendered page and readable text feed an extraction pipeline. This captured opportunity was saved without a model call."}},
    {id:"prepare",label:"Prepare for the role",title:"A resume, with the right context.",description:"Choose a saved role inside the document review. Look past the score to the category explanations and missing terms—useful prompts for an honest revision.",film:"role-aware-document-review",screens:["resume-analysis-breakdown","resume-keywords"],takeaway:{title:"Reasons are more useful than a score alone.",text:"The recording uses the app’s local rule-based fallback. It is a review aid, not an employer ATS assessment or a prediction of hiring success."}},
    {id:"progress",label:"Keep moving",title:"Every opportunity has a next step.",description:"Move an application forward, preserve the conversation in a note, keep documents close and set a follow-up. The pieces stay with the search instead of disappearing into separate tabs.",film:"application-workflow",screens:["pipeline","application-notes","reminders"],takeaway:{title:"Small records add up to continuity.",text:"These changes were persisted through the actual backend in a fictional account. A saved reminder is demonstrated; external reminder delivery is not."}},
  ],
  system:[{title:"Capture at the source",text:"The MV3 extension collects structured, rendered and readable page content with a per-tab capture guard."},{title:"Keep an owned record",text:"Authenticated FastAPI routes connect the posting to a user’s jobs, applications and documents."},{title:"Review in context",text:"Resume text and the selected role feed a content-sensitive cache, local rules and optional providers."},{title:"Account for the work",text:"PostgreSQL records, Redis controls and provider-usage attribution support the application boundary."}],
  decisions:[
    {title:"Extract useful page data before asking a model.",explanation:"The extension gathers JobPosting data, rendered DOM and readable content. The backend merges staged extraction results. A per-tab guard prevents overlapping captures, and a short cache avoids repeating work on the same page.",tradeoff:"A varied web page can still produce missing fields or duplicated description text. The successful HTML path does not establish compatibility with every job board; pasted-text extraction has a separate model requirement.",sources:[{label:"Extension capture",path:"chrome-extension/background.js"},{label:"Extraction orchestration",path:"backend/app/domain/jobs/extraction/service/orchestrator.py"}]},
    {title:"Cache the content, not just the document name.",explanation:"Role-aware analysis keys include document and job IDs plus hashes of resume text and job context. Changing the source material changes the cache identity, even when the underlying record is the same.",tradeoff:"Cached analysis expires after 30 days. The local fallback checks terms, structure and readability heuristics; a higher internal score is not evidence of better hiring outcomes.",sources:[{label:"Analysis cache",path:"backend/app/domain/documents/service/cache.py"},{label:"Rule-based analysis",path:"backend/app/domain/documents/service/analysis.py"}]},
    {title:"Separate request limits from spending guarantees.",explanation:"Provider accounting records user, model, token usage, estimated cost, latency and success. Redis-backed limits and a daily spend check provide operating controls around optional model features.",tradeoff:"The daily budget check fails open if Redis errors, while particular per-user AI limiters fail closed. These controls should not be described as a hard global spending guarantee under concurrent requests or infrastructure failure.",sources:[{label:"Usage accounting",path:"backend/app/infra/external/llm_tracker.py"},{label:"Request limits",path:"backend/app/infra/security/rate_limiter.py"}]},
    {title:"Keep account access close to the data boundary.",explanation:"Current-user resolution loads the account before protected operations; document services check ownership. Session rotation and revocation live in the auth routes. Realtime connections use short-lived, one-use Redis tickets rather than long-lived credentials in the connection URL.",tradeoff:"The captured flows verify one fictional account’s records, not a security audit of every endpoint. The ticket and session lifecycle were source-reviewed; external realtime notification delivery was not demonstrated.",sources:[{label:"Current-user resolution",path:"backend/app/api/deps/auth.py"},{label:"One-use connection tickets",path:"backend/app/infra/security/ws_tickets.py"},{label:"Refresh rotation",path:"backend/app/api/routers/auth/core/refresh.py"}]},
  ],
  boundaries:["The archived source was run locally with PostgreSQL, Redis and fictional account data. This page does not imply an active hosted service or real customer adoption.","The installed extension, saved opportunity and selected-role document analysis were exercised against the real backend. Paid model calls, external email and push delivery were disabled.","The original UI calls document review AI analysis. The recording explicitly labels the actual local rule-based fallback; no model response was fabricated.","The review found incomplete notification, filtering and document-shortcut behavior. Failed paths are documented in the source review and excluded from successful demonstrations."],
};
