import type { ProjectWorld } from "./worlds";
export const arcWorld: ProjectWorld = {
  headline:"A world to learn in. A platform to build on.",description:"Arc connects expressive student activities, instructor-led classrooms, reusable curriculum and program reporting. Together, Arc and Browser Coder serve 3,000+ students, instructors and managers.",motif:"THE CONNECTED LEARNING PLATFORM",roles:["Students","Instructors","Content authors","School & program teams"],hero:"student-space",companion:"visual-flowchart",repo:"https://github.com/ninasokolov8/step-up",revision:"5549bf960754130c6dfe06b0b7bab1fb6a756d7f",privateSource:true,
  stories:[
    {id:"learning-worlds",label:"Learn by doing",title:"Make the learning feel like yours.",description:"Space, Magic Forest and Neon Hacker change the atmosphere around the same learning pathway. Inside it, students make diagrams, connect ideas and submit work that stays inspectable.",film:"learning-worlds-and-making",screens:["student-space","student-magic-forest","visual-flowchart","reflection-cards"],takeaway:{title:"Expression with a consistent learning model.",text:"Five real theme choices share the same student record. Different activity handlers support visual, written and reflective work without turning each theme into a separate curriculum."}},
    {id:"live-classroom",label:"Run the room",title:"One classroom. Two sides of the moment.",description:"A student commits an answer. The instructor reads the room, closes the round and advances. Independent student sessions follow the classroom’s shared state.",film:"live-classroom-two-sides",screens:["live-student-answer","live-instructor-controls"],takeaway:{title:"The server owns the round.",text:"Question identity, active state, membership and duplicate-answer checks protect the session. This recording uses the app’s automatic polling fallback; the WebSocket transport was not exercised."}},
    {id:"curriculum",label:"Build the curriculum",title:"Start with intent. Keep the draft in your hands.",description:"Set a learning goal and activity preferences. Arc assembles a sequence from existing material, then lets the author refine the lessons and see what still needs preparation.",film:"syllabus-from-intent-to-review",screens:["syllabus-preview","teaching-readiness"],takeaway:{title:"Useful automation leaves room for judgment.",text:"Smart Build ranks existing tagged activities with explicit rules. The draft is editable, and readiness warnings expose missing teaching materials before publication or assignment."}},
    {id:"learning-loop",label:"Follow the work",title:"A first version is the beginning.",description:"Keep a student’s submission, the instructor’s published feedback and the next revision connected. School and program views preserve the context behind participation and progress.",film:"learning-loop",screens:["instructor-review","student-revision","program-analytics"],takeaway:{title:"A progress indicator has work behind it.",text:"Drafts, submissions, reviews and revisions are different records. Reporting can summarize the program while keeping the underlying work available to the right people."}},
  ],
  system:[{title:"Different people",text:"Student, instructor, author and management portals resolve a typed actor and the scope of their work."},{title:"Shared learning rules",text:"Curriculum, task handlers and classroom session services give each activity a defined lifecycle."},{title:"Versioned work",text:"Drafts, submitted versions and published reviews retain their relationships as a learner revises."},{title:"A wider perspective",text:"Scoped reporting connects classrooms and programs back to activity, feedback and original submissions."}],
  decisions:[
    {title:"Change the world around the work, not the work itself.",explanation:"The theme registry defines Aurora, Aurora Light, Neon Hacker, Magic Forest and Space. A validated student preference selects the experience; theme resolution has a safe fallback. The learning records do not need to be duplicated for each visual style.",tradeoff:"Themes change navigation, progress treatment and atmosphere. They are presentation choices, not separate games or evidence of improved learning outcomes.",sources:[{label:"Theme registry",path:"src/config/themes.php"},{label:"Theme resolution",path:"src/app/Platform/Domain/Theming/ThemeManager.php"},{label:"Student theme tests",path:"src/tests/Feature/Student/StudentThemeTest.php"}]},
    {title:"Give different activities different submission contracts.",explanation:"The task registry dispatches to specialized handlers. Canvas and flowchart work export visual artifacts; matching stores structured answers; programming has a Browser Coder boundary; shared sessions finalize participation into submissions. Reflection, sorting, questionnaires and external launches have their own paths.",tradeoff:"The canonical enum lists 21 kinds, including games and instructor-led or external activities. That is not a claim of 21 equally complete standalone editors. The films exercise a selected set of native activities.",sources:[{label:"Canonical task kinds",path:"src/app/Platform/Domain/Task/TaskType.php"},{label:"Task handler registry",path:"src/app/Platform/Domain/Task/TaskTypeRegistry.php"},{label:"Flowchart editor",path:"packages/flowchart-editor/src/FlowchartEditor.tsx"}]},
    {title:"Keep late autosave from rewriting a submitted moment.",explanation:"Submission services distinguish draft updates from submitted work. A late autosave does not silently invent a new draft after submission. Published reviews belong to the submitted version, so later student changes do not erase the context the instructor reviewed.",tradeoff:"Each editor must respect that lifecycle. Text revision is demonstrated; the captured flowchart’s new-version editor did not automatically copy the previous editable diagram, so that behavior is not promised here.",sources:[{label:"Submission lifecycle",path:"src/app/Platform/Domain/Submission/SubmissionService.php"},{label:"Visual export",path:"packages/flowchart-editor/src/useExport.ts"}]},
    {title:"Treat a live lesson as shared state with clear transitions.",explanation:"Quiz services validate the current question, membership, active state and timing before accepting an answer. Instructor controls close, advance and end rounds. Other shared modes have distinct rules: moderated word clouds, anonymous-position heatmaps, turn-based debate and branching votes.",tradeoff:"Realtime presentation needs a recovery path. The demonstration uses Arc’s polling fallback with independent browser sessions; it does not establish WebSocket latency or production performance under load.",sources:[{label:"Session lifecycle",path:"src/app/Platform/Domain/QuizBattle/QuizBattleSessionService.php"},{label:"Answer acceptance",path:"src/app/Platform/Domain/QuizBattle/QuizBattleAnswerService.php"},{label:"Student update path",path:"src/resources/js/student-quiz-battle/realtime.js"}]},
    {title:"Separate curriculum assembly, publication and release.",explanation:"The smart draft generator scores existing activities using tags and preferences. An author can edit the result and inspect coverage. Publishing creates a reusable pack; assigning a pack to a class and releasing its lessons are separate operations.",tradeoff:"Preferences influence ranking rather than guaranteeing exclusive task types or hard tag constraints. The captured draft deliberately contains preparation gaps; generation is not proof that a curriculum is ready to teach.",sources:[{label:"Draft generator",path:"src/app/Platform/Domain/ContentBuilder/SmartDraftGeneratorService.php"},{label:"Publishing boundary",path:"src/app/Platform/Domain/ContentBuilder/ContentPackDraftPublishingService.php"},{label:"Lesson release",path:"src/app/Platform/Domain/Lesson/LessonReleaseService.php"}]},
    {title:"Include access scope in the report’s identity.",explanation:"Analytics intersects actor restrictions with the requested reporting scope, then includes that context in cache identity. School views can connect aggregate activity to permitted classrooms and submission previews.",tradeoff:"Participation and learning-friction indicators describe recorded activity. They are not validated educational outcomes, and questionnaire profile labels are not a clinical assessment.",sources:[{label:"Actor restrictions",path:"src/app/Platform/Domain/Analytics/V3/ActorScopeRestrictions.php"},{label:"Analytics service",path:"src/app/Platform/Domain/Analytics/V3/AnalyticsV3Service.php"}]},
  ],
  boundaries:["All displayed schools, people, work and curriculum are fictional local fixtures. Five themes, selected visual activities, a shared quiz and the curriculum builder were exercised through the original UI.","The capture runs development revision 43dfaf6. The final source audit checked 5549bf96; its intervening changes concern delivery configuration, documentation and browser-test timing, with no product UI/domain changes. Production has a separate release.","The curriculum film prepares an editable draft and exposes missing materials. It does not publish a pack, assign it to a class or demonstrate AI-generated pedagogy.","Browser Coder, Arc Gaming, external APIs and paid feedback-assistance providers were source-reviewed but not called from these Arc captures. Detailed source references belong to the private team repository."],
};
