import type { ProjectWorld } from "./worlds";
export const browserWorld: ProjectWorld = {
  headline: "Make the next line make sense.",
  description: "A browser-based programming workbench for learning by doing. Write code, understand a mistake, inspect a running program and watch an idea become a drawing.",
  motif: "THE PROGRAMMING WORKBENCH",
  roles: ["Programming learners", "Teachers", "Learning platforms"],
  hero: "geometry-result", companion: "checks-passing",
  repo: "https://github.com/ninasokolov8/browser-coder", revision: "7d3cae91ff9cc73001d7fcfa0aa3b315cebb2aeb",
  stories: [
    { id:"understand", label:"Learn from feedback", title:"A mistake is a place to start.", description:"A missing colon becomes a clear explanation. A visible repair gets the program moving. Three checks reveal the more interesting question: is the answer actually right?", film:"learning-journey", screens:["error-explained","checks-with-feedback","checks-passing"], takeaway:{title:"Helpful without taking over.",text:"The repair is deliberately narrow. The teacher defines the checks; the learner still makes the change that fixes the reasoning."}},
    { id:"inspect", label:"See the state", title:"Pause. Look closer. Connect the dots.", description:"Run a real Python program, stop at a breakpoint and inspect the values behind the result. Move between recorded pauses to see what changed.", film:"state-journey", screens:["loop-first-value","loop-accumulated-value"], takeaway:{title:"History you can trust.",text:"Previous pauses are recorded views of state. Browsing them does not rewind the running Python process; returning to live restores the current pause."}},
    { id:"draw", label:"Think visually", title:"One loop. A whole new perspective.", description:"Turtle turns an ordinary loop into geometry. Replay the drawing, scrub to a particular step and connect the line of code to the mark it made.", film:"graphics-journey", screens:["geometry-result","geometry-step"], takeaway:{title:"The drawing remembers how it was made.",text:"Replay uses recorded drawing commands and source locations. Inspecting the drawing does not need to execute the program again."}},
    { id:"share", label:"Build & share", title:"The whole project comes along.", description:"HTML and CSS live together in a real workspace. Open the rendered page, then share the exact files so another person can explore an editable copy.", film:"web-journey", screens:["web-workspace","web-preview","shared-workspace"], takeaway:{title:"A stable reference. Room to experiment.",text:"A share freezes the published snapshot. Each recipient gets a local copy, so trying a change leaves the original link intact."}},
  ],
  system:[
    {title:"A local workspace",text:"Monaco edits documents; IndexedDB stores the learner’s files and revision-aware saves."},
    {title:"One command boundary",text:"Run, edit and workspace actions share capability checks, whether invoked by a button, key or host."},
    {title:"Managed execution",text:"The server selects a language adapter and manages a per-run job directory, process and run lifecycle."},
    {title:"State made visible",text:"Output, diagnostics, debugger snapshots and Turtle commands return to their own presentation layers."},
  ],
  decisions:[
    {title:"Share a lifecycle across six different toolchains.",explanation:"A shared pipeline validates the project, admits the run, prepares its temporary workspace and selects the language adapter. Compilation, streamed output, cancellation and cleanup have explicit boundaries. C# supplies a service-owned project and offline NuGet configuration; Python bootstraps its guard separately so the learner’s line numbers remain intact.",tradeoff:"Each run has a separate directory, but jobs share the service’s OS user. Production containment is configured around the API replica, not a container per learner. Interactive runs disable the ordinary wall timeout and rely on stream closure, Stop and output limits; no hostile-code isolation or load benchmark is claimed.",sources:[{label:"Shared pipeline",path:"server/execution/pipeline.mjs"},{label:"Offline C# setup",path:"server/languages/adapters/csharp.mjs"},{label:"Python bootstrap",path:"server/languages/adapters/python.mjs"}]},
    {title:"Let a learning platform set the workspace boundaries.",explanation:"Host messages wait for initialization and are processed in sequence. Replacing a project reconciles files by path and commits files, folders and state together. Editing, file structure, running and panel visibility can be controlled independently through the embedding protocol.",tradeoff:"Origin validation is an integration convention; incoming messages do not verify the sender window against the parent, and outgoing messages can use a wildcard fallback. Embedded instances use fresh local databases. The host owns lasting lesson context; this is not account-based cloud sync.",sources:[{label:"Host message queue",path:"src/integrations/stepup.ts"},{label:"Workspace reconciliation",path:"src/workspace/service.ts"},{label:"Atomic local replacement",path:"src/workspace/store-indexeddb.ts"}]},
    {title:"Save the revision that was actually written.",explanation:"Each document has a debounced, serialized write queue. A save captures content and its revision together; when it completes, only that captured revision is marked saved. Typing during the write remains dirty instead of being mistaken for persisted work.",tradeoff:"Flush has a bounded retry loop and can report that newer edits superseded the save. Storage failures remain visible instead of retrying forever or replacing the live editor buffer.",sources:[{label:"Persistence coordinator",path:"src/workspace/persistence.ts"},{label:"Persistence regression tests",path:"tests/unit/workspace-persistence.test.ts"}]},
    {title:"Make feedback specific enough to act on.",explanation:"Compiler diagnostics take priority over advisory scanner messages on the same line. Error first aid offers only narrowly recognized repairs, such as a missing Python header colon. The test runner accepts a teacher-defined harness and parses pass, fail and skip results into learner feedback.",tradeoff:"The system refuses ambiguous harness selection and uncertain repairs. Hidden harness files are a learner-interface convention, not a secrecy or anti-cheating boundary.",sources:[{label:"Error first aid",path:"src/features/error-first-aid.ts"},{label:"Harness selection",path:"src/features/tests/harness.ts"},{label:"Result protocol",path:"src/features/tests/protocol.ts"}]},
    {title:"Keep recorded history separate from live execution.",explanation:"The debugger retains up to 500 stop snapshots. A history cursor changes the displayed state while the live pause stays intact. Variable comparison is scoped to the displayed file and function, and a new stop returns the view to the live session.",tradeoff:"This is inspection history, not reverse debugging. Recursion can share a comparison frame; the interface does not promise a complete historical heap or replay of every program effect.",sources:[{label:"Stop history",path:"src/features/debug/history.ts"},{label:"Variable differences",path:"src/features/debug/variable-diff.ts"},{label:"Debug lifecycle",path:"src/features/debug/state.ts"}]},
    {title:"Share a snapshot without promising live collaboration.",explanation:"Sharing publishes the current project files and entry point. Opening the link initializes a separate editable workspace. Web preview likewise publishes a multi-file snapshot so relative styles and assets can travel together.",tradeoff:"There are no shared cursors or simultaneous editing. Preview content receives a sandbox policy on the served asset response as well as its wrapper; preview pages can still make permitted network requests.",sources:[{label:"Project sharing",path:"src/features/share.ts"},{label:"Multi-file preview",path:"src/features/live-preview.ts"},{label:"Preview response policy",path:"server/previews/headers.mjs"}]},
  ],
  boundaries:["The films demonstrate real local Python execution, debugging, teacher-defined checks and Turtle replay. The source contains six execution adapters; this is not a claim that all six were exercised in these recordings.","The web preview and shared workspace use a fictional HTML/CSS student project. Its design is sample input, not a built-in Browser Coder template.","Pause history and Turtle replay are distinct features. Source-linked ordinary text output uses print-site heuristics rather than a complete runtime trace.","The local preview route was forwarded to the original API to match the production route arrangement. No application result was mocked. A rename-input issue found during capture is documented in the review and is not shown as a successful workflow."],
};
