import type { ArcExplorerPage, ArcPortalDefinition } from "./types";

const controller = (name: string) =>
  `src/app/Platform/Portals/Instructor/Controllers/${name}.php`;
const service = (name: string) =>
  `src/app/Platform/Portals/Instructor/Services/${name}.php`;
const domain = (path: string) => `src/app/Platform/Domain/${path}.php`;
const originalScreens: Record<string, string[]> = {
  overview: ["instructor-workspace"],
  classroom: ["instructor-classroom"],
  learners: ["instructor-learners"],
  grades: ["instructor-gradebook"],
  insights: ["instructor-statistics"],
};

function page(
  id: string,
  label: string,
  group: string,
  title: string,
  description: string,
  features: string[],
  sourcePaths: string[],
  options: Partial<ArcExplorerPage> = {},
): ArcExplorerPage {
  return {
    id,
    label,
    group,
    title,
    description,
    features,
    sourcePaths,
    filmIds: [],
    ...options,
    screenIds: originalScreens[id] ?? options.screenIds ?? [],
  };
}

export const instructorPortal: ArcPortalDefinition = {
  id: "instructor",
  label: "Instructor",
  subtitle: "Teach, notice, respond",
  description:
    "Follow a classroom from its lesson plan to the individual work, feedback and shared activities inside it.",
  initialPage: "overview",
  pages: [
    page(
      "overview",
      "Teaching desk",
      "Classroom",
      "A clear view before class.",
      "Maya’s fictional teaching desk connects the current lesson, pending work and the people who need a closer look.",
      [
        "Assigned classrooms",
        "Active and completed lessons",
        "Pending review",
        "Instructor questionnaires",
      ],
      [
        controller("InstructorDashboardController"),
        service("InstructorDashboardService"),
      ],
    ),
    page(
      "classroom",
      "Classroom hub",
      "Classroom",
      "One classroom. The full context.",
      "A lesson tree keeps activities, visibility and student work together. Inspect a lesson or activity without changing its state.",
      [
        "Current content pack",
        "Lesson and activity visibility",
        "Entry code and rotation",
        "Student and submission counts",
        "Finished lesson archive",
      ],
      [
        controller("InstructorClassroomController"),
        service("InstructorClassroomSidebarPresenter"),
        domain("Lesson/LessonReleaseService"),
      ],
    ),
    page(
      "classroom/lesson",
      "Decisions & loops",
      "Classroom",
      "Prepare the lesson, then teach it.",
      "The lesson brings its plan, presentation, instructor notes, shared files and programming workspace into one place.",
      [
        "Lesson plan",
        "Presentation slides",
        "Instructor notes",
        "Shared and instructor-only materials",
        "Separate activity release",
      ],
      [
        controller("InstructorClassroomController"),
        "src/app/Platform/Portals/Instructor/ViewModels/InstructorLessonPanelPresenter.php",
        controller("InstructorLessonReleaseController"),
      ],
      { parentId: "classroom" },
    ),
    page(
      "classroom/activity",
      "Activity & student states",
      "Classroom",
      "Who is drafting, submitting or trying again?",
      "The same activity can contain an unfinished draft, a first submission and a later revision. The instructor sees those differences.",
      [
        "Latest submitted version",
        "Draft-only work",
        "Version history",
        "Independent solution visibility",
        "Task-specific previews",
        "Programming and game context",
      ],
      [
        service("InstructorTaskPanelService"),
        controller("InstructorTaskReleaseController"),
      ],
      { parentId: "classroom" },
    ),
    page(
      "learners",
      "Learners",
      "Classroom",
      "Names before numbers.",
      "Find a learner within the instructor’s assigned classrooms, then inspect their activity and feedback history.",
      [
        "Classroom-scoped search",
        "Individual progress",
        "Student work history",
        "Classroom membership",
        "Scoped student account management in the product",
      ],
      [
        controller("InstructorStudentController"),
        service("InstructorClassroomPanelService"),
      ],
    ),
    page(
      "learners/jordan",
      "Jordan’s learning history",
      "Classroom",
      "Jordan’s next step has context.",
      "A fictional learner profile connects submitted work, published feedback and the revision that followed it.",
      [
        "Student detail",
        "Submission versions",
        "Review state",
        "Work across lessons",
      ],
      [
        service("InstructorClassroomPanelService"),
        controller("InstructorSubmissionController"),
      ],
      { parentId: "learners" },
    ),
    page(
      "reviews",
      "Review queue",
      "Learning & feedback",
      "Give the next useful response.",
      "The review queue starts from the latest submitted work. Draft-only work remains a different state.",
      [
        "Pending published reviews",
        "Submission filters",
        "Version selection",
        "Task-specific work viewers",
        "Scoped CSV export in the product",
      ],
      [
        controller("InstructorSubmissionController"),
        service("InstructorClassroomPanelService"),
      ],
      { screenIds: ["instructor-review"] },
    ),
    page(
      "reviews/submission",
      "A revision, side by side",
      "Learning & feedback",
      "Feedback stays beside the work.",
      "Inspect Jordan’s two versions, the requested change and a sample rubric. This read-only example does not submit a grade or publish feedback.",
      [
        "Draft versus published feedback",
        "Revision requests",
        "Rubric criteria and subcriteria",
        "Optional 1–10 star criteria",
        "Empty-work grading guard",
        "Optional AI feedback refinement",
      ],
      [
        controller("InstructorReviewController"),
        service("InstructorReviewService"),
        controller("InstructorAiFeedbackController"),
      ],
      {
        parentId: "reviews",
        screenIds: ["instructor-review", "student-revision"],
      },
    ),
    page(
      "grades",
      "Gradebook",
      "Learning & feedback",
      "A grade is more useful with its state.",
      "A classroom matrix connects a score to the underlying submission, publication state and request for another attempt.",
      [
        "Students × activities",
        "Latest submitted work",
        "Published review states",
        "Revision indicators",
        "Task and learner averages",
      ],
      [
        controller("InstructorReviewController"),
        "src/app/Platform/Portals/Instructor/ViewModels/InstructorGradeMatrixViewModel.php",
      ],
    ),
    page(
      "insights",
      "Learning insights",
      "Learning & feedback",
      "Find the pattern. Keep the context.",
      "Participation, submitted work and reviewed work describe different parts of a lesson. These sample figures are not platform analytics.",
      [
        "Lesson or month grouping",
        "Date, learner and activity filters",
        "Completion and participation",
        "Revision follow-through",
        "Activity-type breakdown",
        "Student-level drilldown",
      ],
      [service("InstructorStatisticsPanelService")],
    ),
    page(
      "materials",
      "Lesson materials",
      "Teaching tools",
      "The right material for each audience.",
      "Explore a sample lesson plan, teaching notes and student handout. In Arc, shared visibility is controlled separately from instructor-only resources.",
      [
        "Lesson and task attachments",
        "Audience labels",
        "Per-classroom visibility",
        "Native file previews",
        "External document viewers where needed",
      ],
      [
        controller("InstructorAttachmentController"),
        "src/app/Platform/Portals/Instructor/ViewModels/InstructorLessonPanelPresenter.php",
      ],
    ),
    page(
      "workspace",
      "Personal code",
      "Teaching tools",
      "Lesson code, with room for your own.",
      "Lesson materials and the instructor’s personal files coexist. Personal files follow the instructor across lessons; restoring lesson materials preserves them.",
      [
        "Browser Coder integration",
        "Lesson-specific master files",
        "Global personal files",
        "Owner-scoped database persistence",
        "Material-only restore",
        "Student and instructor master ZIPs",
      ],
      [
        controller("InstructorSandboxController"),
        domain("Sandbox/InstructorSandboxService"),
      ],
    ),
    page(
      "sessions",
      "Live activities",
      "Teaching tools",
      "Six ways to think together.",
      "Each session family has its own teaching rhythm and live board. Open a sample board to see the differences.",
      [
        "Quiz Battle",
        "Live Cloud",
        "Class heatmap",
        "Structured debate",
        "Team escape room",
        "Branching scenario",
      ],
      ["src/routes/platform/instructor.php"],
      {
        screenIds: ["live-instructor-controls"],
        filmIds: ["live-classroom-two-sides"],
      },
    ),
    page(
      "sessions/quiz",
      "Quiz Battle",
      "Teaching tools",
      "A question, a timer, a shared reveal.",
      "The instructor controls question progression and sees participation before the class moves on.",
      [
        "Waiting room",
        "Question timer",
        "Answer counts",
        "Close and advance states",
        "Leaderboard",
        "Persisted session results",
      ],
      [
        controller("InstructorQuizBattleController"),
        domain("QuizBattle/QuizBattleSessionService"),
      ],
      {
        parentId: "sessions",
        screenIds: ["live-instructor-controls", "live-student-answer"],
        filmIds: ["live-classroom-two-sides"],
      },
    ),
    page(
      "sessions/cloud",
      "Live Cloud",
      "Teaching tools",
      "Make the class’s ideas visible.",
      "Short contributions gather around a prompt. The instructor’s board can move between prompts and moderate individual answers.",
      [
        "Prompt progression",
        "Incoming answers",
        "Answer moderation",
        "Saved cloud layout at session end",
      ],
      [controller("InstructorLiveCloudController")],
      { parentId: "sessions" },
    ),
    page(
      "sessions/heatmap",
      "Class heatmap",
      "Teaching tools",
      "An image becomes a shared question.",
      "Learners place responses on an image. The board gathers their positions to reveal where the class is looking.",
      [
        "Image pages",
        "Position-based responses",
        "Page progression",
        "Aggregate live board",
      ],
      [controller("InstructorHeatmapController")],
      { parentId: "sessions" },
    ),
    page(
      "sessions/debate",
      "Structured debate",
      "Teaching tools",
      "Give each side space to reason.",
      "A round-based board organizes arguments around two positions, with the instructor controlling the sequence.",
      [
        "Two-sided contributions",
        "Rounds",
        "Live contribution updates",
        "Instructor-led progression",
      ],
      [controller("InstructorDebateController")],
      { parentId: "sessions" },
    ),
    page(
      "sessions/escape",
      "Team escape room",
      "Teaching tools",
      "Different teams. A shared challenge.",
      "The instructor can inspect each team’s progress, room state and attempts while the activity unfolds.",
      [
        "Automatic or manual teams",
        "Room and node progression",
        "Pause and resume states",
        "Lockout recovery",
        "Team results",
      ],
      [
        controller("InstructorEscapeRoomController"),
        controller("InstructorEscapeRoomSessionController"),
        controller("InstructorEscapeRoomDashboardController"),
      ],
      { parentId: "sessions" },
    ),
    page(
      "sessions/branching",
      "Branching scenario",
      "Teaching tools",
      "Let a decision shape the lesson.",
      "The class votes on a choice. The instructor selects the next branch and can trace the route to its outcome.",
      [
        "Decision nodes",
        "Class votes",
        "Instructor-selected branch",
        "Traversed path",
        "Leaf outcomes",
      ],
      [controller("InstructorBranchingController")],
      { parentId: "sessions" },
    ),
    page(
      "presentation",
      "Shared presentation",
      "Teaching tools",
      "Keep the lesson on the same page.",
      "A presentation belongs to the active classroom lesson. This sample lets you inspect slides without broadcasting to students.",
      [
        "Active lesson context",
        "Shared slide index",
        "Start and stop broadcast in the product",
        "Next, previous and direct slide navigation",
      ],
      [
        controller("InstructorPresentationController"),
        controller("InstructorLiveLessonController"),
      ],
    ),
    page(
      "peer-review",
      "Peer review",
      "Learning together",
      "Peer feedback with an instructor in the loop.",
      "Assignments connect reviewers to classmates. Responses remain unpublished until the instructor moderates and releases them.",
      [
        "Circular assignment without self-review",
        "1–5 assigned reviews",
        "Manual assignment",
        "Review and closed phases",
        "Response moderation",
        "Individual or batch publication",
      ],
      [
        controller("InstructorPeerReviewController"),
        domain("PeerReview/PeerReviewDistributionService"),
        domain("PeerReview/PeerReviewResponseService"),
      ],
    ),
    page(
      "sharing",
      "Vision-board sharing",
      "Learning together",
      "A window into another classroom, by agreement.",
      "Cross-class vision-board sharing uses a request and approval workflow between instructors, with incoming and outgoing states.",
      [
        "Eligible vision-board activities",
        "Incoming and outgoing requests",
        "Pending, approved, denied and revoked states",
        "Classroom-scoped visibility",
      ],
      [
        controller("InstructorVisionBoardShareController"),
        domain("VisionBoard/VisionBoardShareService"),
      ],
    ),
    page(
      "questionnaires",
      "Questionnaires",
      "Learning together",
      "Two kinds of questionnaire context.",
      "The instructor’s own assigned questionnaires are separate from classroom participation and student result summaries.",
      [
        "Instructor assignments",
        "Own response history",
        "Pending and completed states",
        "Classroom assignment groups",
        "Participation",
        "Configured scoring categories",
      ],
      [
        service("InstructorDashboardService"),
        service("InstructorClassroomService"),
        controller("InstructorQuestionnaireController"),
      ],
    ),
    page(
      "support",
      "Session support",
      "Classroom",
      "Small signals during a busy lesson.",
      "Help requests, recent student activity and the active lesson give the instructor a practical view of what needs attention.",
      [
        "Unresolved help requests",
        "Student and activity context",
        "Recent-activity student list",
        "Active lesson return link",
        "Classroom entry code",
      ],
      [
        controller("InstructorHelpController"),
        domain("Help/HelpService"),
        controller("InstructorDashboardController"),
      ],
    ),
  ],
};
