import type { ArcPortalDefinition } from "./types";

export interface StudentTaskType {
  id: string;
  title: string;
  group: string;
  participation: string;
  summary: string;
  prompt: string;
  features: string[];
  variants: string[];
  sourcePaths: string[];
}

export const studentTaskTypes: StudentTaskType[] = [
  {
    id: "text",
    title: "Write",
    group: "Create & express",
    participation: "Individual",
    summary: "A thoughtful answer, with space to develop it.",
    prompt: "Explain why a program should validate an input before using it.",
    features: [
      "Plain-text response with character count and minimum/maximum length",
      "Debounced draft saving with visible status",
      "A submitted version and published feedback",
    ],
    variants: ["text"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/TextTaskHandler.php",
      "src/resources/views/components/task-types/editors/text.blade.php",
      "src/resources/js/text-task-editor.js",
    ],
  },
  {
    id: "table",
    title: "Fill a structure",
    group: "Create & express",
    participation: "Individual",
    summary: "Turn observations into a useful structure.",
    prompt: "Compare three ways to check a temperature reading.",
    features: [
      "Editable cells alongside teacher-provided locked values",
      "Configurable columns and additional rows",
      "Filled-cell progress and draft/submitted states",
    ],
    variants: ["editable cells", "preset cells", "additional rows"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/TableTaskHandler.php",
      "src/resources/views/components/task-types/editors/table.blade.php",
      "src/resources/js/table-task-editor.js",
    ],
  },
  {
    id: "canvas",
    title: "Drawing canvas",
    group: "Create & express",
    participation: "Individual",
    summary: "Explain an idea in shapes, marks and images.",
    prompt: "Sketch how a sensor connects to a useful everyday object.",
    features: [
      "Drawing, text, stickers and image composition",
      "Fullscreen canvas with JSON state and image preview",
      "Personal image library and mobile capture pathway",
    ],
    variants: ["draw", "text", "images", "stickers"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/CanvasTaskHandler.php",
      "src/resources/views/components/task-types/editors/canvas.blade.php",
      "src/resources/js/canvas-task-editor.js",
    ],
  },
  {
    id: "vision_board",
    title: "Inspiration boards",
    group: "Think & reflect",
    participation: "Individual",
    summary:
      "A sequence of boards that connects past, present and possibility.",
    prompt:
      "Make a visual story of what you have learned and what you want to try.",
    features: [
      "Two to eight configurable canvas panels",
      "Reference material and independent panel drafts",
      "A final sharing caption alongside the visual work",
    ],
    variants: ["multiple canvas panels", "sharing caption"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/VisionBoardTaskHandler.php",
      "src/resources/views/components/task-types/editors/vision-board.blade.php",
      "src/resources/js/vision-board/editor.js",
    ],
  },
  {
    id: "questionnaire",
    title: "Reflection questions",
    group: "Think & reflect",
    participation: "Individual",
    summary: "Different question formats make room for different answers.",
    prompt: "Think about how you approached today’s challenge.",
    features: [
      "One question at a time with progress and previous/next navigation",
      "Short/long text, scale, single-choice and multiple-choice inputs",
      "Saved answers and a submitted version",
    ],
    variants: [
      "short_text",
      "long_text",
      "scale",
      "single_choice",
      "multiple_choice",
    ],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/QuestionnaireTaskHandler.php",
      "src/resources/views/components/task-types/editors/questionnaire.blade.php",
      "src/resources/js/questionnaire-task-editor.js",
    ],
  },
  {
    id: "image_vision_board",
    title: "Image vision board",
    group: "Think & reflect",
    participation: "Individual + shared gallery",
    summary: "Choose images, then make the result your own.",
    prompt: "Choose the images that best represent your learning style.",
    features: [
      "One or several images per configured question",
      "Personal board with backgrounds, card positions, stickers and a note",
      "Class, school, region, national and approved shared gallery scopes",
    ],
    variants: ["single pick", "multiple picks", "personal layout"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/ImageVisionBoardTaskHandler.php",
      "src/resources/views/components/task-types/editors/image-vision-board.blade.php",
      "src/resources/js/image-vision-board-task-editor.js",
    ],
  },
  {
    id: "file",
    title: "File submission",
    group: "Create & express",
    participation: "Individual",
    summary: "Bring work from another tool into the learning record.",
    prompt: "Attach your completed observation sheet.",
    features: [
      "Drag/drop or file selection with a named file preview",
      "Replace or remove a draft attachment",
      "Uploaded work is associated with its submission version",
    ],
    variants: ["document", "image", "attachment"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/FileTaskHandler.php",
      "src/resources/views/components/task-types/editors/file.blade.php",
      "src/resources/js/file-task-editor.js",
    ],
  },
  {
    id: "programming",
    title: "Programming studio",
    group: "Code & solve",
    participation: "Individual + separate IDE",
    summary: "Read it. Complete it. Build something of your own.",
    prompt:
      "Build a helpful study planner: use blocks of at most 25 minutes and handle a non-positive input.",
    features: [
      "Code reading with written explanations",
      "Fill-in-the-blanks with a stitched program",
      "Free code, snippet/project workspaces and Browser Coder integration",
    ],
    variants: ["code_reading", "fill_blanks", "free_code"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/ProgrammingTaskHandler.php",
      "src/resources/views/components/task-types/editors/programming-parts.blade.php",
      "src/resources/js/programming-parts/ide-bridge.js",
    ],
  },
  {
    id: "external",
    title: "External activity",
    group: "Connected tools",
    participation: "External integration",
    summary: "A clear handoff to a resource beyond Arc.",
    prompt: "Explore an interactive circuit resource selected for this lesson.",
    features: [
      "A validated external URL and descriptive launch control",
      "Opens the resource in a separate browsing context",
      "First visit is recorded as a submission/visited state",
    ],
    variants: ["validated URL"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/ExternalTaskHandler.php",
      "src/resources/views/components/task-types/editors/external.blade.php",
      "src/app/Platform/Domain/ExternalActivity/ExternalActivityLaunchService.php",
    ],
  },
  {
    id: "arc_game",
    title: "Arc Gaming Center",
    group: "Connected tools",
    participation: "External integration",
    summary: "An assigned game, connected to the classroom.",
    prompt: "Explore a logic game chosen for the group.",
    features: [
      "Configured game releases in the activity",
      "Server-issued passwordless single-use launch",
      "Classroom synchronization and time-limit/deadline settings",
    ],
    variants: ["game selection", "time-limited launch"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/ArcGameTaskHandler.php",
      "src/resources/views/components/task-types/editors/arc-game.blade.php",
      "src/app/Platform/Portals/Student/Controllers/StudentArcGameController.php",
    ],
  },
  {
    id: "recording",
    title: "Audio & video",
    group: "Create & express",
    participation: "Individual + device capture",
    summary: "Let a learner explain an idea in their own voice.",
    prompt: "Give a short explanation of the decision you made.",
    features: [
      "Audio or video recorder with duration and playback",
      "Permission/error handling and a phone continuation QR flow",
      "Stored recording becomes part of the submitted work",
    ],
    variants: ["audio", "video", "mobile recording"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/RecordingTaskHandler.php",
      "src/resources/views/components/task-types/editors/recording.blade.php",
      "src/resources/js/recording/manager.js",
    ],
  },
  {
    id: "escape_room",
    title: "Team escape room",
    group: "Learn together",
    participation: "Teacher-led team session",
    summary: "A shared puzzle, a sequence of discoveries.",
    prompt: "Help your team unlock the next room by reasoning together.",
    features: [
      "Teams progress through configured rooms",
      "Answer checks, clue gates and timed lockouts",
      "Team-shared clue-master conversation and victory state",
    ],
    variants: ["team puzzle", "clue conversation"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/EscapeRoomTaskHandler.php",
      "src/resources/views/components/task-types/editors/live-activity.blade.php",
      "src/app/Platform/Portals/Student/Controllers/StudentEscapeRoomController.php",
    ],
  },
  {
    id: "live_cloud",
    title: "Live word cloud",
    group: "Learn together",
    participation: "Teacher-led shared session",
    summary: "A roomful of ideas, visible together.",
    prompt: "What makes feedback useful?",
    features: [
      "Student answers contribute to the shared cloud",
      "Own answers can be removed while permitted",
      "Teacher moderation and end-of-session participation records",
    ],
    variants: ["shared cloud", "personal answers"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/LiveCloudTaskHandler.php",
      "src/resources/views/components/task-types/editors/live-cloud.blade.php",
      "src/app/Platform/Portals/Student/Controllers/StudentLiveCloudController.php",
    ],
  },
  {
    id: "sorting_ranking",
    title: "Sort & rank",
    group: "Code & solve",
    participation: "Individual",
    summary: "Make relationships clear by moving ideas into place.",
    prompt: "Arrange an input-validation workflow, then classify its steps.",
    features: [
      "Rank items in sequence or sort them into categories",
      "Multiple sections within one activity",
      "Configured correct arrangements can receive a server-computed score",
    ],
    variants: ["rank", "classify"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/SortingRankingTaskHandler.php",
      "src/resources/views/components/task-types/editors/sorting-ranking.blade.php",
      "src/resources/js/sorting-ranking/editor.js",
    ],
  },
  {
    id: "matching",
    title: "Matching pairs",
    group: "Code & solve",
    participation: "Individual",
    summary: "Connect the pieces and see the pattern.",
    prompt: "Match each programming concept to its purpose.",
    features: [
      "Pair items across two columns with visible connections",
      "Multi-section activity with independent pairs",
      "Submitted result and configured automatic scoring",
    ],
    variants: ["single section", "multiple sections"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/MatchingTaskHandler.php",
      "src/resources/views/components/task-types/editors/matching.blade.php",
      "src/resources/js/matching/interactions.js",
    ],
  },
  {
    id: "class_heatmap",
    title: "Class heatmap",
    group: "Learn together",
    participation: "Teacher-led shared session",
    summary: "See where a class places its thinking.",
    prompt: "Mark the part of a diagram where a check should happen.",
    features: [
      "Point or region selection on configured pages/images",
      "Normalized coordinates shared with the class session",
      "Teacher-controlled session and stored participation on finish",
    ],
    variants: ["point", "region"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/ClassHeatmapTaskHandler.php",
      "src/resources/views/components/task-types/editors/live-activity.blade.php",
      "src/resources/js/student-heatmap/interaction.js",
    ],
  },
  {
    id: "quiz_battle",
    title: "Quiz Battle",
    group: "Learn together",
    participation: "Teacher-led shared session",
    summary: "A fast question, an immediate learning moment.",
    prompt: "Choose the safest result when a sensor value is missing.",
    features: [
      "Question timer with one/multiple correct answer modes",
      "Student answer feedback, score and class leaderboard",
      "Teacher closes questions, advances and ends the session",
    ],
    variants: ["single choice", "multiple choice"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/QuizBattleTaskHandler.php",
      "src/resources/views/components/task-types/editors/quiz-battle.blade.php",
      "src/resources/js/student-quiz-battle/answers.js",
    ],
  },
  {
    id: "branching_scenario",
    title: "Choose a path",
    group: "Code & solve",
    participation: "Individual or class vote",
    summary: "Choices carry the story in a different direction.",
    prompt: "Your prototype fails a test. Which step do you take next?",
    features: [
      "Self-paced choices with path history and an outcome",
      "Alternative class-vote mode with shared counts",
      "The selected path progresses through configured story nodes",
    ],
    variants: ["individual", "class_vote"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/BranchingScenarioTaskHandler.php",
      "src/resources/views/components/task-types/editors/live-activity.blade.php",
      "src/app/Platform/Portals/Student/Controllers/StudentBranchingController.php",
    ],
  },
  {
    id: "flowchart",
    title: "Flowchart builder",
    group: "Create & express",
    participation: "Individual or collaborative",
    summary: "Give a process a shape people can follow.",
    prompt: "Map an input check from reading to a safe result.",
    features: [
      "Shapes, labeled edges, node palette and a minimap",
      "Grid, snapping, starter graphs and configurable node limits",
      "Optional classroom collaboration and PNG submission preview",
    ],
    variants: ["individual", "collaborative"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/FlowchartTaskHandler.php",
      "src/resources/views/components/task-types/editors/flowchart.blade.php",
      "src/app/Platform/Shared/ViewModels/FlowchartTaskEditorViewModel.php",
    ],
  },
  {
    id: "session_finale",
    title: "Session finale",
    group: "Think & reflect",
    participation: "Individual",
    summary: "Finish with a reflection worth keeping.",
    prompt: "Choose a card and name one thing you will try next.",
    features: [
      "Select a configured identity/reflection card",
      "Add a short action reflection",
      "Submitted state shows a completion seal and chosen card",
    ],
    variants: ["card selection", "action reflection"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/SessionFinaleTaskHandler.php",
      "src/resources/views/components/task-types/editors/session-finale.blade.php",
      "src/resources/js/session-finale-task-editor.js",
    ],
  },
  {
    id: "debate",
    title: "Structured debate",
    group: "Learn together",
    participation: "Teacher-led shared session",
    summary: "Take a position, then build an argument.",
    prompt: "Should a prototype favor speed or careful validation?",
    features: [
      "Choose a side and contribute an argument",
      "Instructor-controlled rounds and contribution limits",
      "Shared argument board and final participation record",
    ],
    variants: ["sides", "rounds"],
    sourcePaths: [
      "src/app/Platform/Domain/Task/Handlers/DebateTaskHandler.php",
      "src/resources/views/components/task-types/editors/live-activity.blade.php",
      "src/resources/js/student-debate/submission.js",
    ],
  },
];

export const studentPortal: ArcPortalDefinition = {
  id: "student",
  label: "Student",
  subtitle: "A world for learning",
  description:
    "Follow a learner through lessons, creative work, feedback and shared classroom experiences.",
  initialPage: "overview",
  pages: [
    {
      id: "overview",
      label: "My learning world",
      group: "Learning",
      title: "Your learning world",
      description:
        "A classroom, a personal pathway, and room to make it your own.",
      features: [
        "A real theme system across five environments",
        "Visible lesson and task progress",
        "Direct routes to feedback, reflections and resources",
      ],
      sourcePaths: [
        "src/resources/views/student/dashboard/index.blade.php",
        "src/app/Platform/Portals/Student/ViewModels/StudentDashboardViewModel.php",
      ],
      screenIds: [
        "student-space",
        "student-magic-forest",
        "student-neon-hacker",
        "student-aurora",
        "student-aurora-light",
      ],
      filmIds: ["learning-worlds-and-making"],
    },
    {
      id: "lessons",
      label: "Lessons",
      group: "Learning",
      title: "A path through the classroom",
      description:
        "Move from a lesson’s purpose to its activities, materials and saved work.",
      features: [
        "Lesson availability and visible task states",
        "Theme-specific task navigation",
        "Lesson sandbox and materials",
      ],
      sourcePaths: [
        "src/resources/views/student/lessons/partials/flat-tasks.blade.php",
        "src/resources/views/student/lessons/partials/task-ring.blade.php",
        "src/resources/views/student/lessons/partials/sandbox.blade.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks",
      label: "Activity library",
      group: "Learning",
      title: "Twenty-one ways to take part",
      description:
        "Explore individual work, shared classroom activities and connected tools.",
      features: [
        "All canonical task types remain directly accessible",
        "Three distinct programming formats",
        "Individual, shared and external boundaries are visible",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/TaskType.php",
        "src/resources/views/components/task-types/editor.blade.php",
      ],
      screenIds: [
        "visual-flowchart",
        "matching-connections",
        "reflection-cards",
      ],
      filmIds: [],
    },
    {
      id: "backpack",
      label: "Backpack",
      group: "My workspace",
      title: "Everything within reach",
      description:
        "Lesson resources, reference material and a personal image library.",
      features: [
        "Program, lesson and task attachments",
        "Reusable images uploaded for canvas work",
        "Source-derived resource grouping for this explorer",
      ],
      sourcePaths: [
        "src/resources/views/components/student/materials-disclosure.blade.php",
        "src/app/Platform/Portals/Student/Controllers/TaskAssetController.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "sandbox",
      label: "Code sandbox",
      group: "My workspace",
      title: "A workspace of your own",
      description:
        "Read the lesson files, inspect the program, and see how its pieces fit.",
      features: [
        "Private workspace for each lesson and learner",
        "Browser Coder integration",
        "Restore lesson material while keeping personal files",
      ],
      sourcePaths: [
        "src/app/Platform/Portals/Student/Controllers/StudentSandboxController.php",
        "src/resources/js/sandbox.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "submissions",
      label: "My submissions",
      group: "My workspace",
      title: "The work, and the work before it",
      description:
        "An original attempt stays visible as the next version develops.",
      features: [
        "Per-lesson submission list",
        "Draft and submitted versions",
        "Explicitly start a newer version",
      ],
      sourcePaths: [
        "src/app/Platform/Portals/Student/Controllers/StudentSubmissionController.php",
        "src/app/Platform/Domain/Submission/SubmissionVersionService.php",
      ],
      screenIds: ["matching-saved"],
      filmIds: [],
    },
    {
      id: "feedback",
      label: "Feedback",
      group: "My workspace",
      title: "Feedback that leads somewhere",
      description:
        "See the response, understand the next step, and follow the revision.",
      features: [
        "Latest published feedback per task",
        "Revision-request badges",
        "Published peer reviews with a rubric",
      ],
      sourcePaths: [
        "src/app/Platform/Portals/Student/Services/StudentFeedbackPageService.php",
        "src/app/Platform/Portals/Student/Controllers/StudentPeerReviewController.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "reflections",
      label: "My reflections",
      group: "My perspective",
      title: "A little more self-understanding",
      description:
        "Reflection questions and assigned questionnaire results sit alongside the learning journey.",
      features: [
        "Assigned questionnaire and response profiles",
        "Completed responses and pending assignments",
        "Separate from inline questionnaire task answers",
      ],
      sourcePaths: [
        "src/app/Platform/Portals/Student/Controllers/StudentQuestionnaireController.php",
        "src/app/Platform/Portals/Student/Services/StudentQuestionnaireProfileService.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "vision-board",
      label: "My vision board",
      group: "My perspective",
      title: "Make the board feel like you",
      description:
        "Chosen images become a personal composition, with controlled ways to share it.",
      features: [
        "Editable board styling and card placement",
        "Configured gallery scopes",
        "Cross-device pairing and teacher-approved sharing",
      ],
      sourcePaths: [
        "src/app/Platform/Portals/Student/Controllers/StudentVisionBoardController.php",
        "src/app/Platform/Portals/Student/Services/StudentVisionBoardService.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "live-classroom",
      label: "Live classroom",
      group: "Together",
      title: "A different kind of class participation",
      description:
        "A cloud of ideas, a shared decision, a team challenge or a fast question.",
      features: [
        "Six distinct shared-session experiences",
        "Teacher-controlled question and session lifecycle",
        "Participation becomes part of the learning record",
      ],
      sourcePaths: [
        "src/app/Platform/Portals/Student/Controllers/StudentQuizBattleController.php",
        "src/app/Platform/Portals/Student/Controllers/StudentLiveCloudController.php",
        "src/app/Platform/Portals/Student/Controllers/StudentEscapeRoomController.php",
      ],
      screenIds: ["live-student-answer", "live-instructor-controls"],
      filmIds: ["live-classroom-two-sides"],
    },
    {
      id: "tasks/text",
      label: "Write",
      group: "Activity details",
      parentId: "tasks",
      title: "Write",
      description: "A thoughtful answer, with space to develop it.",
      features: [
        "Plain-text response with character count and minimum/maximum length",
        "Debounced draft saving with visible status",
        "A submitted version and published feedback",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/TextTaskHandler.php",
        "src/resources/views/components/task-types/editors/text.blade.php",
        "src/resources/js/text-task-editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/table",
      label: "Fill a structure",
      group: "Activity details",
      parentId: "tasks",
      title: "Fill a structure",
      description: "Turn observations into a useful structure.",
      features: [
        "Editable cells alongside teacher-provided locked values",
        "Configurable columns and additional rows",
        "Filled-cell progress and draft/submitted states",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/TableTaskHandler.php",
        "src/resources/views/components/task-types/editors/table.blade.php",
        "src/resources/js/table-task-editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/canvas",
      label: "Drawing canvas",
      group: "Activity details",
      parentId: "tasks",
      title: "Drawing canvas",
      description: "Explain an idea in shapes, marks and images.",
      features: [
        "Drawing, text, stickers and image composition",
        "Fullscreen canvas with JSON state and image preview",
        "Personal image library and mobile capture pathway",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/CanvasTaskHandler.php",
        "src/resources/views/components/task-types/editors/canvas.blade.php",
        "src/resources/js/canvas-task-editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/vision_board",
      label: "Inspiration boards",
      group: "Activity details",
      parentId: "tasks",
      title: "Inspiration boards",
      description:
        "A sequence of boards that connects past, present and possibility.",
      features: [
        "Two to eight configurable canvas panels",
        "Reference material and independent panel drafts",
        "A final sharing caption alongside the visual work",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/VisionBoardTaskHandler.php",
        "src/resources/views/components/task-types/editors/vision-board.blade.php",
        "src/resources/js/vision-board/editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/questionnaire",
      label: "Reflection questions",
      group: "Activity details",
      parentId: "tasks",
      title: "Reflection questions",
      description:
        "Different question formats make room for different answers.",
      features: [
        "One question at a time with progress and previous/next navigation",
        "Short/long text, scale, single-choice and multiple-choice inputs",
        "Saved answers and a submitted version",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/QuestionnaireTaskHandler.php",
        "src/resources/views/components/task-types/editors/questionnaire.blade.php",
        "src/resources/js/questionnaire-task-editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/image_vision_board",
      label: "Image vision board",
      group: "Activity details",
      parentId: "tasks",
      title: "Image vision board",
      description: "Choose images, then make the result your own.",
      features: [
        "One or several images per configured question",
        "Personal board with backgrounds, card positions, stickers and a note",
        "Class, school, region, national and approved shared gallery scopes",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/ImageVisionBoardTaskHandler.php",
        "src/resources/views/components/task-types/editors/image-vision-board.blade.php",
        "src/resources/js/image-vision-board-task-editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/file",
      label: "File submission",
      group: "Activity details",
      parentId: "tasks",
      title: "File submission",
      description: "Bring work from another tool into the learning record.",
      features: [
        "Drag/drop or file selection with a named file preview",
        "Replace or remove a draft attachment",
        "Uploaded work is associated with its submission version",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/FileTaskHandler.php",
        "src/resources/views/components/task-types/editors/file.blade.php",
        "src/resources/js/file-task-editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/programming",
      label: "Programming studio",
      group: "Activity details",
      parentId: "tasks",
      title: "Programming studio",
      description: "Read it. Complete it. Build something of your own.",
      features: [
        "Code reading with written explanations",
        "Fill-in-the-blanks with a stitched program",
        "Free code, snippet/project workspaces and Browser Coder integration",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/ProgrammingTaskHandler.php",
        "src/resources/views/components/task-types/editors/programming-parts.blade.php",
        "src/resources/js/programming-parts/ide-bridge.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/external",
      label: "External activity",
      group: "Activity details",
      parentId: "tasks",
      title: "External activity",
      description: "A clear handoff to a resource beyond Arc.",
      features: [
        "A validated external URL and descriptive launch control",
        "Opens the resource in a separate browsing context",
        "First visit is recorded as a submission/visited state",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/ExternalTaskHandler.php",
        "src/resources/views/components/task-types/editors/external.blade.php",
        "src/app/Platform/Domain/ExternalActivity/ExternalActivityLaunchService.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/arc_game",
      label: "Arc Gaming Center",
      group: "Activity details",
      parentId: "tasks",
      title: "Arc Gaming Center",
      description: "An assigned game, connected to the classroom.",
      features: [
        "Configured game releases in the activity",
        "Server-issued passwordless single-use launch",
        "Classroom synchronization and time-limit/deadline settings",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/ArcGameTaskHandler.php",
        "src/resources/views/components/task-types/editors/arc-game.blade.php",
        "src/app/Platform/Portals/Student/Controllers/StudentArcGameController.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/recording",
      label: "Audio & video",
      group: "Activity details",
      parentId: "tasks",
      title: "Audio & video",
      description: "Let a learner explain an idea in their own voice.",
      features: [
        "Audio or video recorder with duration and playback",
        "Permission/error handling and a phone continuation QR flow",
        "Stored recording becomes part of the submitted work",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/RecordingTaskHandler.php",
        "src/resources/views/components/task-types/editors/recording.blade.php",
        "src/resources/js/recording/manager.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/escape_room",
      label: "Team escape room",
      group: "Activity details",
      parentId: "tasks",
      title: "Team escape room",
      description: "A shared puzzle, a sequence of discoveries.",
      features: [
        "Teams progress through configured rooms",
        "Answer checks, clue gates and timed lockouts",
        "Team-shared clue-master conversation and victory state",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/EscapeRoomTaskHandler.php",
        "src/resources/views/components/task-types/editors/live-activity.blade.php",
        "src/app/Platform/Portals/Student/Controllers/StudentEscapeRoomController.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/live_cloud",
      label: "Live word cloud",
      group: "Activity details",
      parentId: "tasks",
      title: "Live word cloud",
      description: "A roomful of ideas, visible together.",
      features: [
        "Student answers contribute to the shared cloud",
        "Own answers can be removed while permitted",
        "Teacher moderation and end-of-session participation records",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/LiveCloudTaskHandler.php",
        "src/resources/views/components/task-types/editors/live-cloud.blade.php",
        "src/app/Platform/Portals/Student/Controllers/StudentLiveCloudController.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/sorting_ranking",
      label: "Sort & rank",
      group: "Activity details",
      parentId: "tasks",
      title: "Sort & rank",
      description: "Make relationships clear by moving ideas into place.",
      features: [
        "Rank items in sequence or sort them into categories",
        "Multiple sections within one activity",
        "Configured correct arrangements can receive a server-computed score",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/SortingRankingTaskHandler.php",
        "src/resources/views/components/task-types/editors/sorting-ranking.blade.php",
        "src/resources/js/sorting-ranking/editor.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/matching",
      label: "Matching pairs",
      group: "Activity details",
      parentId: "tasks",
      title: "Matching pairs",
      description: "Connect the pieces and see the pattern.",
      features: [
        "Pair items across two columns with visible connections",
        "Multi-section activity with independent pairs",
        "Submitted result and configured automatic scoring",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/MatchingTaskHandler.php",
        "src/resources/views/components/task-types/editors/matching.blade.php",
        "src/resources/js/matching/interactions.js",
      ],
      screenIds: ["matching-connections", "matching-saved"],
      filmIds: [],
    },
    {
      id: "tasks/class_heatmap",
      label: "Class heatmap",
      group: "Activity details",
      parentId: "tasks",
      title: "Class heatmap",
      description: "See where a class places its thinking.",
      features: [
        "Point or region selection on configured pages/images",
        "Normalized coordinates shared with the class session",
        "Teacher-controlled session and stored participation on finish",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/ClassHeatmapTaskHandler.php",
        "src/resources/views/components/task-types/editors/live-activity.blade.php",
        "src/resources/js/student-heatmap/interaction.js",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/quiz_battle",
      label: "Quiz Battle",
      group: "Activity details",
      parentId: "tasks",
      title: "Quiz Battle",
      description: "A fast question, an immediate learning moment.",
      features: [
        "Question timer with one/multiple correct answer modes",
        "Student answer feedback, score and class leaderboard",
        "Teacher closes questions, advances and ends the session",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/QuizBattleTaskHandler.php",
        "src/resources/views/components/task-types/editors/quiz-battle.blade.php",
        "src/resources/js/student-quiz-battle/answers.js",
      ],
      screenIds: ["live-student-answer", "live-instructor-controls"],
      filmIds: ["live-classroom-two-sides"],
    },
    {
      id: "tasks/branching_scenario",
      label: "Choose a path",
      group: "Activity details",
      parentId: "tasks",
      title: "Choose a path",
      description: "Choices carry the story in a different direction.",
      features: [
        "Self-paced choices with path history and an outcome",
        "Alternative class-vote mode with shared counts",
        "The selected path progresses through configured story nodes",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/BranchingScenarioTaskHandler.php",
        "src/resources/views/components/task-types/editors/live-activity.blade.php",
        "src/app/Platform/Portals/Student/Controllers/StudentBranchingController.php",
      ],
      screenIds: [],
      filmIds: [],
    },
    {
      id: "tasks/flowchart",
      label: "Flowchart builder",
      group: "Activity details",
      parentId: "tasks",
      title: "Flowchart builder",
      description: "Give a process a shape people can follow.",
      features: [
        "Shapes, labeled edges, node palette and a minimap",
        "Grid, snapping, starter graphs and configurable node limits",
        "Optional classroom collaboration and PNG submission preview",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/FlowchartTaskHandler.php",
        "src/resources/views/components/task-types/editors/flowchart.blade.php",
        "src/app/Platform/Shared/ViewModels/FlowchartTaskEditorViewModel.php",
      ],
      screenIds: ["visual-flowchart"],
      filmIds: [],
    },
    {
      id: "tasks/session_finale",
      label: "Session finale",
      group: "Activity details",
      parentId: "tasks",
      title: "Session finale",
      description: "Finish with a reflection worth keeping.",
      features: [
        "Select a configured identity/reflection card",
        "Add a short action reflection",
        "Submitted state shows a completion seal and chosen card",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/SessionFinaleTaskHandler.php",
        "src/resources/views/components/task-types/editors/session-finale.blade.php",
        "src/resources/js/session-finale-task-editor.js",
      ],
      screenIds: ["reflection-cards"],
      filmIds: [],
    },
    {
      id: "tasks/debate",
      label: "Structured debate",
      group: "Activity details",
      parentId: "tasks",
      title: "Structured debate",
      description: "Take a position, then build an argument.",
      features: [
        "Choose a side and contribute an argument",
        "Instructor-controlled rounds and contribution limits",
        "Shared argument board and final participation record",
      ],
      sourcePaths: [
        "src/app/Platform/Domain/Task/Handlers/DebateTaskHandler.php",
        "src/resources/views/components/task-types/editors/live-activity.blade.php",
        "src/resources/js/student-debate/submission.js",
      ],
      screenIds: [],
      filmIds: [],
    },
  ],
};
