import Link from "next/link";
import type { EngineeringStudy } from "@/content/engineering/types";
import type { Project } from "@/lib/types";
import { formatSpan } from "@/lib/types";
import { EngineeringVisual } from "./EngineeringVisual";
import styles from "./engineering-study.module.css";

export function EngineeringStudyPage({project,study,next}:{project:Project;study:EngineeringStudy;next:Project}){
  return <article className={`shell ${styles.page}`} data-project={project.slug} data-testid="engineering-study">
    <div className={styles.breadcrumb}><Link href="/work">← All work</Link><span>EARLIER ENGINEERING / SOURCE STUDY</span></div>
    <header className={styles.hero}><div><p className={styles.eyebrow}>THE RULES BEHIND THE SOFTWARE</p><h1>{project.title}</h1><p className={styles.intro}>{study.oneLiner}</p><div className={styles.actions}><a href="#capabilities">Explore the system ↓</a><a href={study.repo} target="_blank" rel="noopener noreferrer">Read the source ↗</a></div></div><EngineeringVisual slug={project.slug}/></header>
    <dl className={styles.facts}><div><dt>CONTEXT</dt><dd>{project.team??"University coursework"}</dd></div><div><dt>MY ROLE</dt><dd>{project.role}</dd></div><div><dt>TIMELINE</dt><dd>{formatSpan(project)}</dd></div><div><dt>EVIDENCE</dt><dd>Source reviewed · illustrative diagrams</dd></div></dl>
    <section className={styles.introduction}><div><p className={styles.eyebrow}>AT A GLANCE</p><h2>{study.visualTitle}</h2></div><div><p>{study.summary}</p>{project.snapshot?.contribution&&<details><summary>My contribution +</summary><p>{project.snapshot.contribution}</p></details>}</div></section>
    <section id="capabilities" className={styles.capabilities} aria-labelledby="capabilities-title"><div className={styles.sectionHeading}><p className={styles.eyebrow}>WHAT THE SYSTEM HANDLES</p><h2 id="capabilities-title">The interesting parts.</h2></div><div className={styles.capabilityGrid}>{study.groups.map((group,index)=><section key={group.title}><span className={styles.bigIndex}>{String(index+1).padStart(2,"0")}</span><h3>{group.title}</h3><p>{group.summary}</p>{(group.details.length>0||group.sources.length>0)&&<details><summary>Implementation details <span aria-hidden="true">+</span></summary>{group.details.length>0&&<ul>{group.details.map(detail=><li key={detail}>{detail}</li>)}</ul>}<div className={styles.sources}>{group.sources.slice(0,3).map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.label} ↗</a>)}</div></details>}</section>)}</div></section>
    <section className={styles.engineering} id="deep-dive" aria-labelledby="engineering-title"><div className={styles.sectionHeading}><p className={styles.eyebrow}>STRUCTURE & JUDGMENT</p><h2 id="engineering-title">How the parts fit.</h2></div><div className={styles.nodeGrid}>{study.architecture.nodes.map(node=><div key={node.id}><span aria-hidden="true">◇</span><h3>{node.label}</h3><p>{node.detail}</p>{study.architecture.edges.filter(edge=>edge.from===node.id).length>0&&<small>→ {study.architecture.edges.filter(edge=>edge.from===node.id).map(edge=>study.architecture.nodes.find(n=>n.id===edge.to)?.label??edge.to).join(" / ")}</small>}</div>)}</div><ul className={styles.stack}>{study.stack.map(tool=><li key={tool}>{tool}</li>)}</ul><div className={styles.decisions}>{study.decisions.map(decision=><details key={decision.title}><summary><h3>{decision.title}</h3><span aria-hidden="true">+</span></summary><div><p>{decision.implementation}</p><p className={styles.rationale}><span>WHY IT MATTERS</span>{decision.rationale}</p><div className={styles.sources}>{decision.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.label} ↗</a>)}</div></div></details>)}<details><summary><h3>Scope, limitations & what I would revisit</h3><span aria-hidden="true">+</span></summary><ul>{study.limitations.map(limit=><li key={limit}>{limit}</li>)}</ul></details></div></section>
    <aside className={styles.evidence}><div><p className={styles.eyebrow}>A NOTE ON THE VISUALS</p><p>These diagrams explain the source implementation. They are not screenshots, measured results or a claim that the archived application was run for this review. Design rationales are interpretations of the code unless an original decision is documented.</p></div><a href={`/media/projects/earlier/${study.slug}-research.json`} target="_blank" rel="noopener noreferrer">Full source review ↗<span>Revision {study.revision.slice(0,8)}</span></a></aside>
    <nav className={styles.next} aria-label="Next project"><div><p className={styles.eyebrow}>KEEP EXPLORING</p><Link href={`/work/${next.slug}`}>{next.title} ↗</Link></div><Link href="/work">Back to all work ←</Link></nav>
  </article>;
}
